
name: main

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: setup toolchain
        run: rustup toolchain install stable --profile minimal

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: cargo test
        run: cargo test --all-features

    #   - name: clippy
    #     run: cargo clippy --all --all-features --tests -- -D warnings